services:
  db:
    image: mysql:5.7
    platform: linux/amd64   # ← 追加
    env_file:
      - .env   # ← 追加
      # - .env.production # ←本番用
    environment:
      # MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: gaku10_development
      # MYSQL_COLLATION: utf8mb4_general_ci
      TZ: Asia/Tokyo #追加　RailsとDBのタイムゾーン差を防ぐ
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d  
    ports:   # ← 追加
      - "3306:3306"

  web:
    build: .
    env_file:
      - .env #　←ローカル
      # - .env.production # ←本番用
    volumes:   # ← 追加
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development # ←ローカル
      #  RAILS_ENV: productio #本番用

      #MYSQL_HOST: db
      # MYSQL_DATABASE: gaku10_development
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
    tty: true
    stdin_open: true

volumes:
  db-data:
